README.md, demo/multipart-demo-data.html, etools-ajax.html
This should parse and prepare any object like the example from demo/multipart-demo-data.html and add it in FormData body of etools-ajax;
Experimental feature.
Do not merge yet.
=> Experimental form of objects to be prepared for FormData

README.md, etools-ajax.html
- added some code to automatically refresh expired data
- needs a param to enable or disable it
- currently doesn't work if there is previously cached data
=> (WIP) Automatic data refresh on cache expiry 

etools-ajax.html
- fixed an IE11 issue with empty response bodies
- connects unicef/etools-issues#272
- closes unicef/etools-issues#272
=> feeature(ie-11-fixes):

etools-ajax-request-behavior.html
- fixed missing behavior error
- connects unicef/etools-issues#727
=> Fix linting errors

etools-ajax-request-behavior.html
- connects unicef/etools-issues#744
=> Fix ie error seen as string instead of json obj

etools-ajax-cache-behavior.html
- connects unicef/etools-issues#900
=> Fix old data perssistance issue

bower.json, etools-ajax-request-behavior.html
- fixed an issue with async xhr request being treated as aborted
- connects unicef/etools-issues#930
=> Fix async request error 

bower.json, etools-ajax-cache-mixin.html
- moved Dexie to dev dependencies
- Added check for Dexie loaded
- connects unicef/etools-issues#1020
=> Dexie update

.eslintrc.json, .gitignore, bower.json, etools-ajax-cache-mixin.html, etools-ajax-data-mixin.html, etools-ajax-request-mixin.html, etools-ajax.html, package.json
=> Linting fixes

README.md, etools-ajax-request-mixin.js, etools-ajax-utils.js, etools-iron-request.js, package.json
=> [ch17722]Handle Jwt token

README.md, etools-ajax-utils.js, modules/types.ts
=>  JWT token update

ajax-error-parser.d.ts, ajax-error-parser.js, etools-ajax-utils.js, package-lock.json, package.json, upload-helper.d.ts, upload-helper.js
=> [ch19231]upload method related

README.md, etools-ajax-request-mixin.js, etools-ajax-request.d.ts, etools-ajax-request.js, etools-ajax-utils.js, package-lock.json, package.json
=> [ch17785]Clean up

ajax-error-parser.d.ts, etools-iron-request.d.ts
[ch20685] Lint fixes on the d.ts files in common components
=> [ch20685] Lint fixes on the d.ts files in common components

ajax-error-parser.js, package-lock.json, package.json
=> [ch21710]Fix display for error {partner: {289:{questions:{1:["wrong type for smth"]}}}}

README.md, analysis.json, etools-ajax-request-mixin.d.ts, etools-ajax-request-mixin.js, etools-ajax-request.d.ts, etools-ajax-request.js, etools-iron-request.d.ts, etools-iron-request.js, upload-helper.js
Clean up old code for progress, [ch17771] etools-ajax / Show upload progress
=> Clean up old code for progress, [ch17771] etools-ajax / Show upload progress

README.md, analysis.json, etools-ajax-request-mixin.d.ts, etools-ajax-request-mixin.js, etools-ajax-request.d.ts, etools-ajax-request.js, etools-iron-request.d.ts, etools-iron-request.js, package-lock.json, package.json, upload-helper.d.ts, upload-helper.js
[ch17771] etools-ajax / Show upload progress
=> [ch17771] etools-ajax / Show upload progress

ajax-error-parser.js, package-lock.json, package.json
=> [ch27743]Handle 403 error

package-lock.json, package.json
=> [ch31751]Update etools-dexie-caching

ajax-error-parser.js, package-lock.json, package.json
[ch32484] Update toasts related to Headquarters Contribution
=> [ch32484] Update toasts related to Headquarters Contribution

ajax-error-parser.js, package-lock.json, package.json
=> [ch33170]Translate some err messages(4.4.2)

README.md, etools-ajax-utils.js, package-lock.json, package.json
=> [ch33668]Send language in request header
